# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
export AWS_ACCESS_KEY_ID='<%= @access_key %>'
export AWS_SECRET_ACCESS_KEY='<%= @secret_access_key %>'
export AWS_REGION='<%= @region %>'
